# Generated by Django 3.2.12 on 2023-12-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20231218_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
