# Generated by Django 3.2.12 on 2023-12-21 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20231222_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
