# Generated by Django 3.2.12 on 2023-12-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20231222_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
