# Generated by Django 3.2.12 on 2024-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20231222_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='tags',
        ),
        migrations.AddField(
            model_name='notes',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
