# Generated by Django 3.2.12 on 2024-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20240215_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
