# Generated by Django 3.2.12 on 2024-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20240216_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
